"""Data models for French Anki Generator."""

from dataclasses import dataclass
from typing import Optional


@dataclass
class VocabularyItem:
    """Represents a single French vocabulary item with all generated data.

    Attributes:
        word: The French word or phrase.
        meaning: Vietnamese meaning (from input file).
        example_fr: Example sentence in French (generated by LLM).
        example_vi: Vietnamese translation of the example (generated by LLM).
        word_audio_path: Path to the word pronunciation audio file.
        failed: Whether this item failed during processing.
        error_message: Description of the error if failed.
    """

    word: str
    meaning: str = ""
    example_fr: str = ""
    example_vi: str = ""
    word_audio_path: Optional[str] = None
    failed: bool = False
    error_message: str = ""

    @property
    def is_complete(self) -> bool:
        """Check if all required data has been generated."""
        return bool(
            self.meaning
            and self.example_fr
            and self.example_vi
            and not self.failed
        )

    @property
    def has_word_audio(self) -> bool:
        """Check if word audio has been generated."""
        return self.word_audio_path is not None
